spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tungns
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  secret-key: top-secret-key